global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'laravel'
    metrics_path: /metrics
    static_configs:
      - targets: ['laravel.test:80']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
